api_v1_authors:
    path:     /
    defaults: { _controller: "AppBundle:Author:index" }

api_v1_authors_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Author:show" }

api_v1_authors_new:
    path:     /new
    defaults: { _controller: "AppBundle:Author:new" }

api_v1_authors_create:
    path:     /create
    defaults: { _controller: "AppBundle:Author:create" }
    methods:  POST

api_v1_authors_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Author:edit" }

api_v1_authors_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Author:update" }
    methods:  [POST, PUT]

api_v1_authors_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Author:delete" }
    methods:  [POST, DELETE]
