AppBundle\Entity\Author:
  type: entity
  table: author
  repositoryClass: AppBundle\Entity\Repositories\AuthorRepository

  id:
    id:
      type:         integer
      generator:    { strategy: AUTO }
  fields:
    name:
        type:         string
        length:       255

    birthday:
        type: datetime

    description:
        type: text

    created_at:
        type: datetime
        gedmo:
          timestampable:
          on: create

    updated_at:
        type: datetime
        gedmo:
          timestampable:
          on: update


